# Generated by Django 3.2.8 on 2022-07-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20220710_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_activation_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='ключ активации'),
        ),
    ]
